services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: marketplace-cake-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      net-apply:
        ipv4_address: 172.24.0.2

volumes:
  postgres_data:

networks:
  net-apply:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/24